# Generated by Django 3.0.1 on 2019-12-31 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('nombre', models.CharField(max_length=100)),
                ('hashtag', models.CharField(max_length=500)),
                ('ganador', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=500)),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteos.Sorteo')),
            ],
        ),
    ]
